spring:
  application:
    name: goods-service
  cloud:
    nacos:
      server-addr: 47.106.155.227:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wenbin123456
    url: jdbc:mysql://localhost:3306/db_test01?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
server:
  port: 7070

logging:
  path: ./logs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
